drop table if exists ${var:DB}.lineitem;
create external table ${var:DB}.lineitem 
(L_ORDERKEY BIGINT,
 L_PARTKEY BIGINT,
 L_SUPPKEY BIGINT,
 L_LINENUMBER INT,
 L_QUANTITY DOUBLE,
 L_EXTENDEDPRICE DOUBLE,
 L_DISCOUNT DOUBLE,
 L_TAX DOUBLE,
 L_RETURNFLAG STRING,
 L_LINESTATUS STRING,
 L_SHIPDATE STRING,
 L_COMMITDATE STRING,
 L_RECEIPTDATE STRING,
 L_SHIPINSTRUCT STRING,
 L_SHIPMODE STRING,
 L_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE 
LOCATION '${var:LOCATION}/lineitem';

drop table if exists ${var:KUDU_DB_NAME}.lineitem;
CREATE TABLE ${var:KUDU_DB_NAME}.lineitem
PRIMARY KEY (L_ORDERKEY)
-- PARTITION BY HASH(L_LINENUMBER) PARTITIONS 8
STORED AS KUDU
AS SELECT * FROM ${var:DB}.lineitem; 

drop table if exists ${var:DB}.part;
create external table ${var:DB}.part (P_PARTKEY BIGINT,
 P_NAME STRING,
 P_MFGR STRING,
 P_BRAND STRING,
 P_TYPE STRING,
 P_SIZE INT,
 P_CONTAINER STRING,
 P_RETAILPRICE DOUBLE,
 P_COMMENT STRING) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE 
LOCATION '${var:LOCATION}/part/';

drop table if exists ${var:KUDU_DB_NAME}.part;
CREATE TABLE ${var:KUDU_DB_NAME}.part
PRIMARY KEY (P_PARTKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.part;

drop table if exists ${var:DB}.supplier;
create external table ${var:DB}.supplier (S_SUPPKEY BIGINT,
 S_NAME STRING,
 S_ADDRESS STRING,
 S_NATIONKEY BIGINT,
 S_PHONE STRING,
 S_ACCTBAL DOUBLE,
 S_COMMENT STRING) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE 
LOCATION '${var:LOCATION}/supplier/';

drop table if exists ${var:KUDU_DB_NAME}.supplier;
CREATE TABLE ${var:KUDU_DB_NAME}.supplier
PRIMARY KEY (S_SUPPKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.supplier;

drop table if exists ${var:DB}.partsupp;
create external table ${var:DB}.partsupp (PS_PARTKEY BIGINT,
 PS_SUPPKEY BIGINT,
 PS_AVAILQTY INT,
 PS_SUPPLYCOST DOUBLE,
 PS_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE
LOCATION'${var:LOCATION}/partsupp';

drop table if exists ${var:KUDU_DB_NAME}.partsupp;
CREATE TABLE ${var:KUDU_DB_NAME}.partsupp
PRIMARY KEY (PS_PARTKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.partsupp;

drop table if exists ${var:DB}.nation;
create external table ${var:DB}.nation (N_NATIONKEY BIGINT,
 N_NAME STRING,
 N_REGIONKEY BIGINT,
 N_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE
LOCATION '${var:LOCATION}/nation';

drop table if exists ${var:KUDU_DB_NAME}.nation;
CREATE TABLE ${var:KUDU_DB_NAME}.nation
PRIMARY KEY (N_NATIONKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.nation;

drop table if exists ${var:DB}.region;
create external table ${var:DB}.region (R_REGIONKEY BIGINT,
 R_NAME STRING,
 R_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE
LOCATION '${var:LOCATION}/region';

drop table if exists ${var:KUDU_DB_NAME}.region;
CREATE TABLE ${var:KUDU_DB_NAME}.region
PRIMARY KEY (R_REGIONKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.region;

drop table if exists ${var:DB}.customer;
create external table ${var:DB}.customer (C_CUSTKEY BIGINT,
 C_NAME STRING,
 C_ADDRESS STRING,
 C_NATIONKEY BIGINT,
 C_PHONE STRING,
 C_ACCTBAL DOUBLE,
 C_MKTSEGMENT STRING,
 C_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE
LOCATION '${var:LOCATION}/customer';

drop table if exists ${var:KUDU_DB_NAME}.customer;
CREATE TABLE ${var:KUDU_DB_NAME}.customer
PRIMARY KEY (C_CUSTKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.customer;

drop table if exists ${var:DB}.orders;
create external table ${var:DB}.orders (O_ORDERKEY BIGINT,
 O_CUSTKEY BIGINT,
 O_ORDERSTATUS STRING,
 O_TOTALPRICE DOUBLE,
 O_ORDERDATE STRING,
 O_ORDERPRIORITY STRING,
 O_CLERK STRING,
 O_SHIPPRIORITY INT,
 O_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS TEXTFILE
LOCATION '${var:LOCATION}/orders';

drop table if exists ${var:KUDU_DB_NAME}.orders;
CREATE TABLE ${var:KUDU_DB_NAME}.orders
PRIMARY KEY (O_ORDERKEY)
STORED AS KUDU
AS SELECT * FROM ${var:DB}.orders;
